### ISSUE TITLE
[PHP] Error: Required parameter $filter follows optional parameter $userId at /var/www/nextcloud/apps/sharelisting/lib/Service/SharesList.php#193 

### ISSUE THREAD

**Issue by ernolf** [nextcloud/sharelisting#368]
Nextcloud 25.0.2
php-fpm: 8.0.26

Flooding logfile.

**Comment by nicknight47** [comment]
fixed for now with

public function getFormattedShares(string $userId = null, int $filter, string $path = null, string $token = null): \Iterator {
