### ISSUE TITLE
Release for NC 26

### ISSUE THREAD

**Issue by rainerjung** [nextcloud/sharelisting#383]
Please provide a release for deployment with NC 26.

**Comment by q-wertz** [comment]
I think in general a few new releases need to be done. Last release is from July 2022, afterwards are some commits that seem important :sweat_smile: 
e.g. Adapt to NC25: 4712b04b48dfad0065c57ac3a8d554e1c8d21839

**Comment by ferfebles** [comment]
Please, release a new version with support for NC26.

This app is extremely usefull in supporting share problems with our users.

**Comment by gonzalo** [comment]
I would say, "release it for NC27!" Just found this app and is so useful for our audits

**Comment by gonzalo** [comment]
I forgot to mention that I manually installed on NC27 and it seems to works fine.

**Comment by menace133780** [comment]
in 26.0.7 the "php occ sharing:list" command is not working, although the app is enabled in the NC backend;
`Command "sharing" is not defined.

  Did you mean one of these?
      sharing:cleanup-remote-storages
      sharing:delete-orphan-shares
      sharing:expiration-notification`
